### ISSUE TITLE
Manual Time Picking (for refinements) at inflection point tangent/trough/peak

### ISSUE THREAD

**Issue by DaloroAT** [DaloroAT/first_break_picking#18]

**Comment by HHTC0** [comment]
@DaloroAT please see the details below, if you decide to refine it further. It nothing some I would require but having this could be helpful to someone else.


In seismology, the inflection point tangent time is the time at which the tangent line to the seismic wave curve changes its direction of curvature. This point is often used to pick the arrival time of a seismic wave, such as a refraction arrival. The peak time is the time at which the seismic wave amplitude reaches its maximum value, and the trough time is the time at which the amplitude reaches its minimum value.

To pick the inflection point tangent time, you can first identify the peak and trough times. Then, draw a tangent line to the seismic wave curve at the midpoint between the peak and trough times. The inflection point tangent time is the time at which this tangent line intersects the x-axis.

The peak and trough times can be identified by looking for the points on the seismic wave curve where the amplitude changes sign. The inflection point tangent time is often located between the peak and trough times, but it can also be located before or after the peak or trough times.

The inflection point tangent time is a useful tool for picking the arrival time of seismic waves. It is especially useful for picking refraction arrivals, which are often difficult to pick because they have a gradual onset.

Here are some additional things to keep in mind when picking the inflection point tangent time:

The inflection point tangent time should be picked as accurately as possible. This is because the accuracy of the arrival time pick will depend on the accuracy of the inflection point tangent time pick.
The inflection point tangent time may not always be easy to identify. This is especially true for seismic waves with a noisy signal.
In some cases, there may be multiple inflection points in a single seismic wave. In these cases, the inflection point tangent time that should be picked is the one that is closest to the peak or trough time.
I hope this helps!
[https://en.wikipedia.org/wiki/Inflection_point](url)
